baseurl = "https://terezalacerda.github.io/guiadosmusiqueiros/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5
publishDir = "docs/"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "Guia dos Musiqueiros"
    subtitle = "Analisando dados musicais"
    keywords = ""
    copyright = ""
    menuMore = "Mostrar mais"
    writtenBy = "Escrito por"
    readMore = "Leia mais"
    readOtherPosts = "Veja mais posts"
    newerPosts = "Posts novos"
    olderPosts = "Posts antigos"
    minuteReadingTime = "min de leitura"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Guia dos Musiqueiros"
      logoHomeLink = "https://terezalacerda.github.io/guiadosmusiqueiros/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/sobre"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
